version: '3.8'

networks:
  biblioteca-net:

services:
  db:
    image: postgres:15-alpine
    container_name: biblioteca_db
    environment:
      POSTGRES_DB: biblioteca_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    networks:
      - biblioteca-net
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
