networks:
  biblioteca-net:

services:
  admin-service:
    build: ./admin-service
    container_name: admin_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/biblioteca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - biblioteca-net

  librarian-service:
    build: ./librarian-service
    container_name: librarian_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/biblioteca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - biblioteca-net

  user-service:
    build: ./user-service
    container_name: user_service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/biblioteca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - biblioteca-net

  frontend:
    build: ./frontend
    container_name: biblioteca_frontend
    ports:
      - "5173:5173"
    networks:
      - biblioteca-net
    volumes:
      - ./frontend:/app
      - /app/node_modules

