networks:
  biblioteca-net:

services:
  db:
    image: postgres:15-alpine
    container_name: biblioteca_db
    environment:
      POSTGRES_DB: biblioteca_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    networks:
      - biblioteca-net
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d biblioteca_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  admin-service:
    build: ./admin-service
    container_name: admin_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/biblioteca_DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - biblioteca-net
    depends_on:
      db:
        condition: service_healthy

  librarian-service:
    build: ./librarian-service
    container_name: librarian_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/biblioteca_DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - biblioteca-net
    depends_on:
      db:
        condition: service_healthy

  user-service:
    build: ./user-service
    container_name: user_service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/biblioteca_DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - biblioteca-net
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: biblioteca_frontend
    ports:
      - "5173:5173"
    networks:
      - biblioteca-net
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pg_data:
